### ISSUE TITLE
Openvpn Validation fails

### ISSUE THREAD

**Issue by Gobiviswa** [openwisp/netjsonconfig#130]
Hi,

Is there any way to skip the backend validation for openvpn? I am not following the way how JSON schema expects.  I don't want to change my DB Schema which is working good for long time. So I want to skip the OpenVPN backend schema validation. is that possible?

**Comment by nemesisdesign** [comment]
This doesn't sound too good, but if you really want to do it you can create a custom OpenVPN backend in which the `validate` method does nothing.

For further questions, please use the [support channels](http://openwisp.org/support.html). We use this as a bug tracker.
