### ISSUE TITLE
[openvpn] format of remote host should allow both hostname and ipv4

### ISSUE THREAD

**Issue by okraits** [openwisp/netjsonconfig#132]
A remote host can be a hostname or an ip address. Right now only a hostname is valid:
https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/backends/openvpn/schema.py#L445

I tried with:
```
                                    "host": {
                                        "type": "string",
                                        "maxLength": 63,
                                        "minLength": 1,
                                        "oneOf": [
                                            {"format": "hostname"},
                                            {"format": "ipv4"},
                                        ],
                                        "propertyOrder": 1,
                                    },
```
But that doesn't work.
@nemesisdesign Any idea?

**Comment by nemesisdesign** [comment]
Annoying problem, maybe we can just remove the `format` validation since it doesn't seem to be doable in a simple manner.

**Comment by okraits** [comment]
Or maybe better: use a pattern to check for the two possible format options.

**Comment by nemesisdesign** [comment]
Yes, let's use a pattern.

**Comment by nemesisdesign** [comment]
I wonder if the new version of jsonschema solves this. #139

**Comment by PabloCastellano** [comment]
Did you trying `anyOf` instead of `oneOf`?

**Comment by nemesisdesign** [comment]
@PabloCastellano I tried it and it works but it needs some CSS adjustment in openwisp-controller because the UI breaks. Thanks for the tip!

**Comment by nemesisdesign** [comment]
So, the problem does not lie in this library.
Using an hostname works fine.
The problem manifests when using the advanced mode of openwisp-controller.

**Comment by nemesisdesign** [comment]
PS: See https://github.com/openwisp/netjsonconfig/pull/158 for confirmation of my claim.
