### ISSUE TITLE
[dependencies] Drop support for python 2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#140]
Set travis to test on python 3.7.
Drop support for python 2 and its constructs.
Simplify `super()` calls.

**Comment by Minecraftian14** [comment]
Can I chat here<I mean discuss the issue>? Sorry I am new here...
What is travis? Would you say this issue is easy for a 3.7 coder?
Does the task only involve replacing the super calls?
Do we have to do this to all files?
