### ISSUE TITLE
[netjsonconfig-tests] Avoid error logging to print noisy output during tests

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#150]
Depends on https://github.com/openwisp/openwisp-utils/issues/98.

Use the decorators mentioned in the issue linked above to silence the output of noisy tests.

**Comment by lehone-hp** [comment]
Hello, 
when I run the tests, I get the following output
```
....................................................................................................................................................................................................................................................................................................Unrecognized config block was skipped:

{
    "unrecognized": true
}


.....................................................
----------------------------------------------------------------------
Ran 345 tests in 10.715s

OK

```
Please how can I know the exact test that runs and generates the output, `Unrecognized config block was skipped` for example like an additional parameter that I can append to the `./runtests.py`

**Comment by 2001asjad** [comment]
@lehone-hp  I wanted to ask how exactly did you come to know that what file in the tests folder we have to use the decorators in ?

**Comment by lehone-hp** [comment]
> @lehone-hp I wanted to ask how exactly did you come to know that what file in the tests folder we have to use the decorators in ?

I ran the tests with the `-v` flag; `./runtests.py -v`, it lists all the tests methods as they run.

**Comment by 2001asjad** [comment]
> > @lehone-hp I wanted to ask how exactly did you come to know that what file in the tests folder we have to use the decorators in ?
> 
> I ran the tests with the `-v` flag; `./runtests.py -v`, it lists all the tests methods as they run.

@lehone-hp but when I run `./runtests.py -v` command for solving issue [https://github.com/openwisp/openwisp-controller/issues/187](url) to know which test methods are giving noisy outputs I get this error :

![Screenshot from 2021-01-09 11-45-35](https://user-images.githubusercontent.com/60435499/104085191-465abb00-5273-11eb-99c8-26893ea221d2.png)
Can you help me out in this ?
`./runtests.py` shows this : 

![8Jansecond](https://user-images.githubusercontent.com/60435499/104085204-72763c00-5273-11eb-9753-df4e5b92ea76.png)

Thank You

**Comment by lehone-hp** [comment]
@2001asjad try, `python runtests.py -v 2`

**Comment by 2001asjad** [comment]
> @2001asjad try, `python runtests.py -v 2`

It works thank you so very much @lehone-hp 😊
