### ISSUE TITLE
http://netjsonconfig.openwisp.org/en/raspbian redirects to scam site

### ISSUE THREAD

**Issue by krangm** [openwisp/netjsonconfig#154]
http://netjsonconfig.openwisp.org/en/raspbian redirects to http://ww25.nodeshot.org/?z in any browser including tor

using https helps but check your site

**Comment by nemesisdesign** [comment]
Related to #143, I fixed master but forgot that this affected those two experimental branches (raspbian and airos) which have not been merged yet. I'm testing a fix. Thanks for reporting.

**Comment by nemesisdesign** [comment]
Should be fixed (clear browser cache if the problem persists).

```
curl http://netjsonconfig.openwisp.org/en/raspbian/ | grep -c nodeshot
0

curl http://netjsonconfig.openwisp.org/en/airos/ | grep -c nodeshot
0

```

Thanks :+1:
