### ISSUE TITLE
[change] Add missing ciphers AES-xxx-GCM for TLS

### ISSUE THREAD

**Issue by mikysal78** [openwisp/netjsonconfig#172]
https://github.com/openwisp/netjsonconfig/blob/53bb4ccfd1a2ba52624396f7afc9c35f18b29267/netjsonconfig/backends/openvpn/schema.py#L105-L139

```bash
# openvpn --show-ciphers
AES-128-CBC  (128 bit key, 128 bit block)
AES-192-CBC  (192 bit key, 128 bit block)
AES-256-CBC  (256 bit key, 128 bit block)
AES-128-GCM  (128 bit key, 128 bit block, TLS client/server mode only)
AES-192-GCM  (192 bit key, 128 bit block, TLS client/server mode only)
AES-256-GCM  (256 bit key, 128 bit block, TLS client/server mode only)
```
Openvpn versions (2.4.7)
how to do?
Thanks

**Comment by nemesisdesign** [comment]
Thanks for reporting @mikysal78, seems some ciphers from the newer versions of OpenVPN are missing, we need to add them to the schema.
