### ISSUE TITLE
[compatiblity] Jinja 3.0 changes PackageLoader usage  

### ISSUE THREAD

**Issue by atb00ker** [openwisp/netjsonconfig#189]
The [PackageLoader usage](https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/backends/base/renderer.py#L22) would break in Jinga 3.0 (which is now used by openwisp-users on master branch); hence we should upgrade this.

Jinja 3.0 Changelog: https://jinja.palletsprojects.com/en/3.0.x/changes/
Affecting change: `Use PEP 451 API to load templates with PackageLoader. #1168`
PEP 451: https://www.python.org/dev/peps/pep-0451/
Issue: https://github.com/pallets/jinja/issues/1168

Sample error with current code:
![cap](https://user-images.githubusercontent.com/24985760/118315623-5fba8f00-b513-11eb-969e-1df1a9e2c35c.png)

**Comment by nemesisdesign** [comment]
> The [PackageLoader usage](https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/backends/base/renderer.py#L22) would break in Jinga 3.0 (which is now used by openwisp-users on master branch);

@atb00ker are you sure of this? I mean, openwisp-users AFAIK does not depend on Jinja, could you point out to me the line of code where it is being used?

**Comment by atb00ker** [comment]
Oops, I meant openwisp-user installs Jinja 3.0, I have to manually downgrade it to avoid this error in openwisp-controller.
In the future, openwisp-controller will also install Jinja 3.0 then we will see the error shown in the screenshot!
