### ISSUE TITLE
[change] Add signalrate option for modem manager interface 

### ISSUE THREAD

**Issue by pandafy** [openwisp/netjsonconfig#226]
The `signalrate` option seems missing from the model manager interface. 
Refer https://openwrt.org/docs/guide-user/network/wan/wwan/modemmanager#use

**Comment by nemesifier** [comment]
Fixed by https://github.com/openwisp/netjsonconfig/pull/229/commits/16b634e3f1e8327739fa0e06f927568652b169e7.
