### ISSUE TITLE
[bug] The LED mode is supposed to be a list not an option

### ISSUE THREAD

**Issue by mfoxworthy** [openwisp/netjsonconfig#227]
I am configuring some custom LED status options and I ran into an issue. When I configure the LED with OpenWISP it provides this output:

package system

config led 'led_lte'
	option dev 'wwan0'
	option mode 'link'
	option name 'LTE'
	option sysfs 'gree:wan'
	option trigger 'netdev'
	
When I configure the LED on OpenWRT if provides this configuration:

config led 'led_lte'
	option name 'LTE'
	option trigger 'netdev'
	option sysfs 'green:wan'
	option dev 'wwan0'
	list mode 'link'
	list mode 'tx'
	list mode 'rx'

When I manually switch to list with the OpenWISP configuration it starts to work.

**Comment by nemesisdesign** [comment]
@mfoxworthy see this passage from https://openwrt.org/docs/guide-user/base-system/led_configuration 

> mode | string | yes | (none) | One or more of link, tx, or rx, seperated by spaces
> -- | -- | -- | -- | --

Mode: One or more of link, tx, or rx, seperated by spaces.

> 
> ### WLAN led
> 
> ```
> config 'led' 'wlan_led'
> 	option 'name'           'WLAN'
> 	option 'sysfs'          'tl-wr1043nd:green:wlan'
> 	option 'trigger'        'netdev'
> 	option 'dev'            'wlan0'
> 	option 'mode'           'link tx rx'
> ```

Therefore, in your configuration, set mode as `"link tx rx"` and according to the OpenWrt docs it should work.

@okraits 

> The relevant project for this issue is https://github.com/openwisp/netjsonconfig. Could you please open an issue in that project?

We can move the issue without asking users to close and recreate it.

**Comment by okraits** [comment]
> We can move the issue without asking users to close and recreate it.

I didn't know that - thank you for the hint :-)

**Comment by mfoxworthy** [comment]
> @mfoxworthy see this passage from https://openwrt.org/docs/guide-user/base-system/led_configuration
> 
> > mode
> > string
> > yes
> > (none)
> > One or more of link, tx, or rx, seperated by spaces
> 
> Mode: One or more of link, tx, or rx, seperated by spaces.
> 
> > ### WLAN led
> > ```
> > config 'led' 'wlan_led'
> > 	option 'name'           'WLAN'
> > 	option 'sysfs'          'tl-wr1043nd:green:wlan'
> > 	option 'trigger'        'netdev'
> > 	option 'dev'            'wlan0'
> > 	option 'mode'           'link tx rx'
> > ```
> 
> Therefore, in your configuration, set mode as `"link tx rx"` and according to the OpenWrt docs it should work.

You are correct. I just tested this with success. Sorry for the bother. Maybe I should read the docs some more. 😳
