### ISSUE TITLE
[bug] Adding modem manager network interface doesn't work with OpenWRT 21.02.2/3 with both PPP and QMI drivers loaded.

### ISSUE THREAD

**Issue by mfoxworthy** [openwisp/netjsonconfig#228]
I have two devices both using a Quectel EC-25 AF. These units use Qualcomm chips and support QMI. If I configure modem manager with OpenWRT using QMI support, the device activates and connects. When I use OpenWISP and update the configuration it stops working.

Working OpenWRT Configuration:

```
config interface 'lte'
	option proto 'modemmanager'
	option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
	option apn 'broadband'
	option auth 'none'
	option metric '20'
	option signalrate '5'
	option iptype 'ipv4'
```

Here is a log of the device starting up with the working configuration:

```
Mon May  2 12:56:50 2022 daemon.notice netifd: Interface 'lte' is setting up now
Mon May  2 12:56:50 2022 daemon.notice netifd: lte (15707): modem available at /org/freedesktop/ModemManager1/Modem/0
Mon May  2 12:56:50 2022 daemon.notice netifd: lte (15707): starting connection with apn 'broadband'...
Mon May  2 12:56:50 2022 daemon.info [2870]: <info>  [modem0] simple connect started...
Mon May  2 12:56:50 2022 daemon.info [2870]: <info>  [modem0] simple connect state (3/8): enable
Mon May  2 12:56:50 2022 daemon.info [2870]: <info>  [modem0] state changed (disabled -> enabling)
Mon May  2 12:56:50 2022 daemon.info [2870]: <info>  [modem0] power state updated: on
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] simple connect state (4/8): wait to get fully enabled
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] state changed (enabling -> enabled)
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] simple connect state (5/8): register
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] 3GPP registration state changed (unknown -> registering)
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] 3GPP registration state changed (registering -> home)
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] state changed (enabled -> registered)
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] simple connect state (6/8): bearer
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] simple connect state (7/8): connect
Mon May  2 12:56:51 2022 daemon.info [2870]: <info>  [modem0] state changed (registered -> connecting)
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7] QMI IPv4 Settings:
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7]     address: XXXXX
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7]     gateway: XXXXX
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7]     DNS openwisp/openwisp-controller#1: XXXXX
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7]     DNS openwisp/openwisp-controller#2: XXXXX
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0/bearer7]        MTU: 1500
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0] state changed (connecting -> connected)
Mon May  2 12:56:52 2022 daemon.info [2870]: <info>  [modem0] simple connect state (8/8): all done
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): successfully connected the modem
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): setting signal refresh rate to 5 seconds
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): Successfully setup extended signal information retrieval
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): network operator name: T-Mobile
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): network operator MCCMNC: 310260
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): registration type: home
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): access technology: lte
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): signal quality: 76%
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): IPv4 connection setup required in interface lte: static
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): adding IPv4 address XXXXX, netmask 255.255.255.192
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): adding default IPv4 route via XXXXX
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): adding primary DNS at XXXXX
Mon May  2 12:56:52 2022 daemon.notice netifd: lte (15707): adding secondary DNS at XXXXX
Mon May  2 12:56:52 2022 daemon.notice netifd: Interface 'lte' is now up
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: reading /tmp/resolv.conf.d/resolv.conf.auto
Mon May  2 12:56:52 2022 daemon.notice netifd: Network device 'wwan0' link is up
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain test
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain onion
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain localhost
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain local
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain invalid
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain bind
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using only locally-known addresses for domain lan
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using nameserver XXXXX
Mon May  2 12:56:52 2022 daemon.info dnsmasq[28672]: using nameserver XXXXX
Mon May  2 12:56:54 2022 user.notice firewall: Reloading firewall due to ifup of lte (wwan0)
```

Here is the OpenWISP configuration in JSON:

```json
{
    "interfaces": [
        {
            "type": "modem-manager",
            "apn": "brodband",
            "device": "",
            "iptype": "ipv4",
            "name": "lte",
            "disabled": false,
            "network": "lte"
        }
    ]
}
```
Here is the generated OpenWRT configuration from OpenWISP:

package network

```
config interface 'lte'
	option apn 'brodband'
	option enabled '1'
	option ifname 'lte'
	option iptype 'ipv4'
	option proto 'modemmanager'
```

The ifname option is not supported in modem manager configurations. OpenWRT transitioned to the new device configurations. Please refer to this link for details:

[https://openwrt.org/docs/guide-user/base-system/basic-networking](url)

Here is the configuration after it is applied to the OpenWRT router.

```
config interface 'lte'
        option auth 'none'
        option apn 'brodband'
        option enabled '1'
        option ifname 'lte'
        option iptype 'ipv4'
        option proto 'modemmanager'
```

So two things, ifname is not supported and the device was not automatically added. There is a note in the template that says to leave that field blank to use the default. Maybe I'm doing it wrong but I tried it 3 times. 

![Screen Shot 2022-05-02 at 1 22 05 PM](https://user-images.githubusercontent.com/8184748/166320486-6decb7d4-4779-4aaa-bd4b-c1692dc5731f.png)

UPDATE: During this test I discovered something I wasn't seeing before. I had both the serial PPP/3G and the QMI drivers loaded in first test. I upgraded my image to add the OpenWISP IPKs but this new image only had the QMI drivers in it. That changed the device name to "/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1" from "/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.2". The only thing I had to do was remove the ifname from the configuration and the interface came up, even after reboot. So I'm not sure what we want to do about this. Modem manager supports both PPP/3G and QMI. Some people operate with the PPP drivers because they tend to be more stable yet they use the QMI driver to use the uqmi utility.  Essentially in a hybrid mode. That isn't supported by the modem manager configuration. Until these modes are supported, I'd add a note to the configuration template or in the README for interfaces that either QMI or PPP/3G drivers should be installed but not both. Furthermore if PPP drivers are used, the LTE monitor items will not appear. 

So the changes I think we need are the following:

Change the ifname to the newer device config in the global network configuration like this:

```
config device 'lte'
        option mtu '1428'
        option name 'wwan0'
``` 

Provide a selection dropdown that offers PPP/QMI/Hybrid so the correct device name is device option is used. It should also add a hook in the interfaces.lua lib that can detect which mode is used so the statistics are referenced correctly. For example, if I have PPP operating at the network layer, I can still see the statistics in the QMI driver. Also, those same values are available in most LTE modems in some form or fashion. It would be a nice addition to support more than just QMI.

Also add the signalrate to the template. 

Please contact me for further work if you need some more testing. This project has gotten so good. I am truly amazed at how fast the features came together. Bravo!

**Comment by nemesisdesign** [comment]
@mfoxworthy can you please provide the full `/etc/config/network` file and remove any sensitive info?

**Comment by mfoxworthy** [comment]
```
config interface 'wifinet0'
	option auto '1'
	option enabled '1'
	option ifname 'wlan0'
	option mtu '1500'
	option proto 'none'

config interface 'wifinet1'
	option auto '1'
	option enabled '1'
	option ifname 'wlan1'
	option mtu '1500'
	option proto 'none'

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd44:3cbe:ebc3::/48'

config device 'device_lan'
	option name 'br-lan'
	option type 'bridge'
	option hash_max '512'
	option igmp_snooping '1'
	option last_member_interval '100'
	option mtu '1500'
	option multicast_querier '1'
	option query_interval '12500'
	option query_response_interval '1000'
	option robustness '2'
	list ports 'eth0'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr 'XXXX'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option auto '1'
	option enabled '1'

config interface 'wan'
	option device 'eth1'
	option proto 'dhcp'
	option metric '10'

config interface 'wan6'
	option device 'eth1'
	option proto 'dhcpv6'

config switch 'switch0'
	option enable_vlan '1'
	option name 'switch0'
	option reset '1'

config switch_vlan 'switch0_vlan1'
	option device 'switch0'
	option ports '3 4 0'
	option vlan '1'

config interface 'lte'
	option apn 'XXXX'
	option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
	option enabled '1'
	option iptype 'ipv4'
	option proto 'modemmanager'
	option signalrate '5'
```
Working:

```
      usb-modeswitch
      kmod-mii
      kmod-usb-net
      kmod-usb-wdm
      kmod-usb-net-qmi-wwan
      uqmi
```
Breaks it:
```
      kmod-usb-serial-option
      kmod-usb-serial
      kmod-usb-serial-wwan
```
The serial modules allow us to use stty and serial commands to check for messages and balance. We can see messages with the uqmi application but we integrated stty with our scripts. We can't get usage data with uqmi.

**Comment by nemesisdesign** [comment]
@mfoxworthy, so, if you try the following:

```
config interface 'lte'
	option apn 'XXXX'
	option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
	option enabled '1'
	option iptype 'ipv4'
	option proto 'modemmanager'
	option signalrate '5'
        option mtu '1420'
```

Is the MTU value honored?

**Comment by mfoxworthy** [comment]
No. I just tried it. Here is the link to the parameters modem manager will accept:

https://openwrt.org/docs/guide-user/network/wan/wwan/modemmanager

When using qmi mode the kmod driver creates an interface called wwan0. If we want to set the MTU o that device, we'd need a option name 'wwan0' section with option mtu '1428':

```
config device
	option name 'wwan0'
	option mtu '1428'
	option ipv6 '0'
```
Openwrt only uses device sections now. With qmi /sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2.1 translates to /dev/cdc-wdm0 which is tied to wwan0.

With the serial drivers a device with the name ppp0 is created and a completely different syspath is used in modem manager.

**Comment by nemesisdesign** [comment]
So, to summarize for @pandafy, I think the following NetJSON:

```json
{
    "interfaces": [
        {
            "type": "modem-manager",
            "apn": "brodband",
            "device": "/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1",
            "iptype": "ipv4",
            "name": "wwan0",
            "disabled": false,
            "signalrate": 5,
            "mtu": 1428
        }
    ]
}
```

Shall generate the following UCI config on OpenWrt:

```
config interface 'wwan0'
	option apn 'brodband'
	option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
	option enabled '1'
	option iptype 'ipv4'
	option proto 'modemmanager'
	option signalrate '5'

config device `device_wwan0`
	option name 'wwan0'
	option mtu '1428'
```

@mfoxworthy do you confirm? We'll implement a fix and ask you to test it.

**Comment by mfoxworthy** [comment]
> So, to summarize for @pandafy, I think the following NetJSON:
> 
> ```json
> {
>     "interfaces": [
>         {
>             "type": "modem-manager",
>             "apn": "brodband",
>             "device": "/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1",
>             "iptype": "ipv4",
>             "name": "wwan0",
>             "disabled": false,
>             "signalrate": 5,
>             "mtu": 1428
>         }
>     ]
> }
> ```
> 
> Shall generate the following UCI config on OpenWrt:
> 
> ```
> config interface 'wwan0'
> 	option apn 'brodband'
> 	option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
> 	option enabled '1'
> 	option iptype 'ipv4'
> 	option proto 'modemmanager'
> 	option signalrate '5'
> 
> config device `device_wwan0`
> 	option name 'wwan0'
> 	option mtu '1428'
> ```
> 
> @mfoxworthy do you confirm? We'll implement a fix and ask you to test it.

I confirm that will work. Most excellent!

**Comment by pandafy** [comment]
Hey @mfoxworthy! I have created a fix for this issue in #229. Can you help us test this? 

If you have installed OpenWISP using ansible-openwisp2, then follow these instructions to install netjsonconfig from that branch: 

1. SSH into the remote machine where OpenWISP is installed 
2. Elevate to superuser status using `sudo su`
3. Activate the python virtual environment 
```
source /opt/openwisp2/env/bin/activate
```
4. Install netjsonconfig from the `issues/228-modem-manager-dsa` branch 
```
pip install -U --no-cache-dir https://github.com/openwisp/netjsonconfig/tarball/issues/228-modem-manager-dsa
```
5. Restart all services to use the updated netjsonconfig module
```
supervisorctl restart all
```

After following above steps, you can log into OpenWISP and create configuration for your devices. I have also added the `signalrate` option in the schema.

**Comment by mfoxworthy** [comment]
> supervisorctl restart all

```
config interface 'lte'
        option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
        option enabled '1'
        option iptype 'ipv4'
        option proto 'modemmanager'
        option signalrate '5'
        option apn 'broadband'
        option lowpower '0'
        option metric '20'

config device 'device_lte'
        option mtu '1500'
        option name 'wwan0'
```
New branch was installed and new configuration was added.

**Confirmed to work! Great Job and fast turn around! You guys rock!**

BTW, I don't know if you have looked into it but option ifname has gone away and option device replaced it. Luci will fix it and it isn't really broken but just thought I'd mention it. I wouldn't have even noticed if I didn't have some users who use Luci. This screen will pop up:

![Screen Shot 2022-05-10 at 9 44 41 AM](https://user-images.githubusercontent.com/8184748/167680378-d9334b92-0e20-4edb-aa7f-db1f40042570.png)


```config interface 'wifinet0'
	option auto '1'
	option enabled '1'
        option ifname 'wlan0' <--- should be "option device 'wlan0'" for OpenWrt 21.02+
	option mtu '1500'
	option proto 'none'

**Comment by nemesisdesign** [comment]
> > supervisorctl restart all
> 
> ```
> config interface 'lte'
>         option device '/sys/devices/platform/soc/8af8800.usb3/8a00000.dwc3/xhci-hcd.0.auto/usb1/1-1'
>         option enabled '1'
>         option iptype 'ipv4'
>         option proto 'modemmanager'
>         option signalrate '5'
>         option apn 'broadband'
>         option lowpower '0'
>         option metric '20'
> 
> config device 'device_lte'
>         option mtu '1500'
>         option name 'wwan0'
> ```
> 
> New branch was installed and new configuration was added.
> 
> **Confirmed to work! Great Job and fast turn around! You guys rock!**

Thanks for confirming!

> BTW, I don't know if you have looked into it but option ifname has gone away and option device replaced it. Luci will fix it and it isn't really broken but just thought I'd mention it. I wouldn't have even noticed if I didn't have some users who use Luci. This screen will pop up:
> 
> ![Screen Shot 2022-05-10 at 9 44 41 AM](https://user-images.githubusercontent.com/8184748/167680378-d9334b92-0e20-4edb-aa7f-db1f40042570.png)
> 
> ```
> 	option auto '1'
> 	option enabled '1'
>         option ifname 'wlan0' <--- should be "option device 'wlan0'" for OpenWrt 21.02+
> 	option mtu '1500'
> 	option proto 'none'
> ```

@mfoxworthy can you please open a new issue for this in which you specify the configuration you are using for that?

**Comment by mfoxworthy** [comment]
I will. I was thinking you may have already seen this so I waited for your confirmation.
