### ISSUE TITLE
[bug] Failing to create a template with more than one bridged interface

### ISSUE THREAD

**Issue by okraits** [openwisp/netjsonconfig#242]
I'm trying to create a template with 3 bridged interfaces. We are using the old pre-DSA syntax.

If I save the template, the second and third bridged interface are reverted to network interfaces. Here is the raw output of the template after saving:
![grafik](https://user-images.githubusercontent.com/5543887/197555090-f910fecd-535c-4d6c-bc3d-b69f97b9f420.png)

Nevertheless, the template seems to be saved with the bridged interfaces in the database, because the device config contains the three bridged interfaces:
![grafik](https://user-images.githubusercontent.com/5543887/197556129-c75d007b-81bc-4897-a6a1-14e818751a5e.png)

**Comment by nemesisdesign** [comment]
@okraits can you please share the NetJSON configuration that can be used to replicate the issue and explain the steps, eg:

- click on add a new template
- paste this NetJSON config
- hit save

Expected result: ...
Actual result: ...

**Comment by nemesisdesign** [comment]
Closing for now, if you have more info on how to replicate this bug please reopen.
