### ISSUE TITLE
OpenVPN tls_auth enabling behavior

### ISSUE THREAD

**Issue by kosli** [openwisp/netjsonconfig#250]
What is the expected behavior if the tls-auth (#174) on the OpenWISP server config gets activated **after** the client config template has already been generated? Should the client template automatically be updated or how can the tls-auth config be manually added to the client template?

**Comment by nemesisdesign** [comment]
Not sure I fully understand the question, I think you mean how to enable tls-auth on already existing templates.
You can do so via advanced mode or from the upper right button in the configuration editor which lists the available options which can be enabled.
Please ask further questions in the https://gitter.im/openwisp/general or on the mailing list, we reserve github issues for development work only (bugs, features, changes, maintenance).

**Comment by kosli** [comment]
Thanks @nemesisdesign  I have had manually updated the template. So there is no way to automatically update the template if the "VPN Servers" have been updated..
