### ISSUE TITLE
[BUG] "management frame protection" can no longer be set to required for certain encryptions

### ISSUE THREAD

**Issue by SerialVelocity** [openwisp/netjsonconfig#264]
Split out from #254 

> **SerialVelocity:**
> another issue is the 2 has been removed from:
> https://github.com/openwisp/netjsonconfig/blob/1.0.2/netjsonconfig/schema.py#L496
> 
> which affects wpa2/wpa3 mixed mode. Quite a big issue if you have multiple SSIDs because if you have a WPA3 SSID with required 802.11w, and a WPA2/WPA3 mixed mode SSID with optional 802.11w, then your speed will drop from ~770Mbps to ~150Mbps.

> **nemesisdesign:**
> Doesn't mfp have to be optional in mixed mode? Can it be required and work on WPA2 too? Not sure I understood 100%.

> **SerialVelocity:**
> Afaik, the "pmf is required" extension came before wpa3 was a thing:
> https://en.wikipedia.org/wiki/IEEE_802.11w-2009
> 
> I can't find anywhere that says pmf has to be optional for mixed mode as it can already be required for just wpa2. Could you point me to where you have seen that be the case? (I haven't explicitly tried connecting with wpa2 when mixed mode is enabled and pmfs are required)

> **nemesisdesign:**
> I can't find the information anymore right now, can you please create a separate issue for this other subject? We should look at what LuCI (the web interface of OpenWrt) does and just follow along.

Another thing that I noticed is that the "options" block still lists `required` as a valid title, but just the `2` option was removed.

**Comment by nemesisdesign** [comment]
Thanks for reporting @SerialVelocity, https://github.com/openwisp/netjsonconfig/pull/267 should fix it.
The bug was introduced by a seemingly unintentional mistake, at least this is my conclusion.
