### ISSUE TITLE
[bug] Africa/Cairo Timezone missing (others may be missing too)

### ISSUE THREAD

**Issue by momothefox** [openwisp/netjsonconfig#287]
In a template, Configuration Menu > General > timezone
missing Africa/Cairo 
Please add.

**Comment by nemesifier** [comment]
Thanks for reporting @momothefox, I moved the issue to the relevant repositories.
I found the timezone list supported by the OpenWrt web UI here: https://github.com/openwrt/luci/blob/master/modules/luci-lua-runtime/luasrc/sys/zoneinfo/tzdata.lua
We should make sure we have all of these in the schema.
Patching the schema is easy if you need a quickfix for your installation, the file is here: https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/backends/openwrt/timezones.py.
