### ISSUE TITLE
Could we get a 1.0.3 release please? :)

### ISSUE THREAD

**Issue by mattiasb** [openwisp/netjsonconfig#303]
Hi!

I just did a `pipx install netjsonconfig` to play around with and
see if I can use `netjsonconfig` for keeping my OpenWRT config under version control.

Specifically I tried:
```console
$ netjsonconfig --native ./backup.tgz --backend openwrt --method json`
```

I get a `KeyError: 'hwmode'` failure at `backends/openwrt/converters/radios.py:117` though.

Cloning the repository I see that this issue [was fixed a year ago](https://github.com/openwisp/netjsonconfig/commit/9dbbbf0e7f9ffab7d77c5b83b684da91b55d2ebc).

So could we get a 1.0.3 please? :)

Also thanks for this project, it's looking pretty neat!

**Comment by nemesifier** [comment]
We're working on the new release of OpenWISP, sorting out release blockers, [updating the documentation](https://github.com/openwisp/openwisp2-docs/pull/189), preparing the changelogs. It's taking time: it's many thousands lines of code, many changes, lots of docs to update.

In the meantime you can install from master, eg: `pip install https://github.com/openwisp/netjsonconfig/tarball/master`.

Thanks for your understanding.
