### ISSUE TITLE
[openwrt] Drop "enabled" logic in OpenVpnRenderer in 0.6.0

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#58]
Solve the issues explained by the comments marked as `TODO` in https://github.com/openwisp/netjsonconfig/commit/7a152a344333665bbc9217011418ae39e8a1af81.

**Comment by jack17529** [comment]
@nemesisdesign ok sir I will solve them.

**Comment by nemesisdesign** [comment]
@jack17529 I did not specify that this must be done in the `0.6.0` release, not now. It's a reminder for a minor cleanup. Thanks anyway.

**Comment by jack17529** [comment]
@nemesisdesign  so should I not touch the code?

**Comment by nemesisdesign** [comment]
@jack17529 no it's not needed. I'll take care of it. I suggest you to find ways to contribute that are more useful to us. Stuff I don't have time to do, finding new bugs. Triaging tickets. Whatever you can do to help out.

**Comment by jack17529** [comment]
@nemesisdesign  roger that .
