### ISSUE TITLE
[openwrt] Missing zonename attribute

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#61]
The `OpenWrt` backend does not generate the `zonename` attribute.

**Comment by ritwickdsouza** [comment]
What is `zonename `? Is it different from `timezone`? Could you give a sample code for generating the bug ?

**Comment by nemesisdesign** [comment]
@ritwickdsouza look in the OpenWRT docs: https://wiki.openwrt.org/doc/uci/system; to replicate the bug write a test in which you assert for the presence of the `zonename` attribute. The value should be generated from timezone.

**Comment by ritwickdsouza** [comment]
So whenever `timezone` attribute is defined. Both `timezone` and `zonename` must be rendered. Right ?

**Comment by nemesisdesign** [comment]
Yes

**Comment by ritwickdsouza** [comment]
Could you help point out where exactly the output generated and places where changes needs to be made ? I'm having some trouble understanding the codebase.

**Comment by nemesisdesign** [comment]
@ritwickdsouza: https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/backends/openwrt/renderers.py#L265-L277

**Comment by nemesisdesign** [comment]
I suggest you to write a failing test first (Test Driven Development), you have to add it to this file:
https://github.com/openwisp/netjsonconfig/blob/master/tests/openwrt/test_system.py

See the documentation regarding how to run tests.

**Comment by nemesisdesign** [comment]
Fixed by #65
