### ISSUE TITLE
[GSoC17] Raspbian backend phase 1

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#78]
@ritwickdsouza: 

- Design and create schema for Raspbian backend
- Start Converters
- Start Renderers
- Tests
- Start documentation page

**Comment by ritwickdsouza** [comment]
On it !

**Comment by nemesisdesign** [comment]
@ritwickdsouza what's up with this issue?

I would like you to finalize what you have been doing in the first phase and merge it. What about documentation page?

**Comment by ritwickdsouza** [comment]
I will compile everthing and improve the documentations now. Will update you soon about this.

**Comment by ritwickdsouza** [comment]
Refer to #79
