### ISSUE TITLE
[GSoC17] Raspbian backend phase 2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netjsonconfig#79]
@ritwickdsouza 

- Generate /etc/resolv.conf using Jinja2
- Generate /etc/hostapd/hostapd.conf using Jinja2
- Generate tar.gz file to install on Raspbian
- Improve tests
- Improve documentation
- First release

**Comment by nemesisdesign** [comment]
@ritwickdsouza how far are we from achieving this?

**Comment by ritwickdsouza** [comment]
@nemesisdesign WPA2 Enterprise and some advanced wireless features and modes like multiple ssids, wds mode are remaining. All other basic configurations can be generated. 
Generating tar.gz file is also done. I will once have to test tar.gz files for more complex NetJSON Device Configurations.
Documentations needs to be updated after scripts can be generated.

**Comment by nemesisdesign** [comment]
Generate methods are ready right?

Work to introduce a basic customized schema for the backend so that all extra required attributes are present in the schema and enforced during validation.

This way we can proceed with a first release of the backend, we will have to write in the documentation page that this backend is experimental and so on.

**Comment by ritwickdsouza** [comment]
The backend can generate Raspbian config files for various basic configurations. For more details have a look at http://netjsonconfig.openwisp.org/en/raspbian/backends/raspbian.html.

The backend can also generate tar.gz files to be installed on Raspbian
