### ISSUE TITLE
[openwrt] missing "vid" option in "switch"

### ISSUE THREAD

**Issue by cappe87** [openwisp/netjsonconfig#85]
The configuration shown in [the programmable switch example](http://netjsonconfig.openwisp.org/en/stable/backends/openwrt.html#programmable-switch-settings) doesn't work.

I needed to add the `vid` attribute to the [netjson](http://netjson.org), eg:

```json
{
    "switch": [
        {
            "name": "switch0",
            "reset": true,
            "vlan": [
                {
                    "device": "switch0",
                    "vlan": 4,
                    "ports": "4t 6t",
                    "vid": "170"
                }
            ],
            "enable_vlan": true
        }
    ]
}
```

**Comment by nemesisdesign** [comment]
After doing some research, I propose the following solution:

I can automatically generate the `vid` option from the `vlan` field but allow to override this automatic behaviour by explicitly setting `vid`.

In the docs I will explain this behaviour in detail with a couple of examples.

What do you think @cappe87?
